package cztongcheng.dev.liuxiaocong.cztongcheng.GreendaoGen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cztongcheng.dev.liuxiaocong.cztongcheng.Home.News.TitleModel;

import cztongcheng.dev.liuxiaocong.cztongcheng.GreendaoGen.TitleModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig titleModelDaoConfig;

    private final TitleModelDao titleModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        titleModelDaoConfig = daoConfigMap.get(TitleModelDao.class).clone();
        titleModelDaoConfig.initIdentityScope(type);

        titleModelDao = new TitleModelDao(titleModelDaoConfig, this);

        registerDao(TitleModel.class, titleModelDao);
    }
    
    public void clear() {
        titleModelDaoConfig.getIdentityScope().clear();
    }

    public TitleModelDao getTitleModelDao() {
        return titleModelDao;
    }

}
